classdef (Sealed) EarthOrientation
    %EarthOrientation - Supplied ECI-to-ECF parameters for version-two DESs
    %   OBJ = EarthOrientation(Name=VALUE) holds the 32 polar-wander and UT
    %   parameters in Appendix M. TA_POLE and TB_UT retain exact 19-character
    %   Julian-date text (seven integer and eleven fractional digits).
    %   Coefficients and periods are doubles in the specified units.
    %
    %   Each attitude or ephemeris DES retains its own parameters. No coordinate
    %   transformation, time conversion or parameter estimation is performed.
    %
    %   See also CSATTB, CSEPHB

    properties
        ta_pole {mustBeAscii(ta_pole,19)} = ''
        a_pole {mustBeMetadata(a_pole,-1,1,0)} = NaN
        b_pole {mustBeMetadata(b_pole,-1,1,0)} = NaN
        cj1_pole {mustBeMetadata(cj1_pole,-1,1,0)} = NaN
        cj2_pole {mustBeMetadata(cj2_pole,-1,1,0)} = NaN
        dj1_pole {mustBeMetadata(dj1_pole,-1,1,0)} = NaN
        dj2_pole {mustBeMetadata(dj2_pole,-1,1,0)} = NaN
        pj1_pole {mustBeMetadata(pj1_pole,0,500,0)} = NaN
        pj2_pole {mustBeMetadata(pj2_pole,0,500,0)} = NaN
        e_pole {mustBeMetadata(e_pole,-1,1,0)} = NaN
        f_pole {mustBeMetadata(f_pole,-1,1,0)} = NaN
        gk1_pole {mustBeMetadata(gk1_pole,-1,1,0)} = NaN
        gk2_pole {mustBeMetadata(gk2_pole,-1,1,0)} = NaN
        hk1_pole {mustBeMetadata(hk1_pole,-1,1,0)} = NaN
        hk2_pole {mustBeMetadata(hk2_pole,-1,1,0)} = NaN
        pk1_pole {mustBeMetadata(pk1_pole,0,500,0)} = NaN
        pk2_pole {mustBeMetadata(pk2_pole,0,500,0)} = NaN
        tb_ut {mustBeAscii(tb_ut,19)} = ''
        i_ut {mustBeMetadata(i_ut,-1,1,0)} = NaN
        j_ut {mustBeMetadata(j_ut,-1,1,0)} = NaN
        kn1_ut {mustBeMetadata(kn1_ut,-1,1,0)} = NaN
        kn2_ut {mustBeMetadata(kn2_ut,-1,1,0)} = NaN
        kn3_ut {mustBeMetadata(kn3_ut,-1,1,0)} = NaN
        kn4_ut {mustBeMetadata(kn4_ut,-1,1,0)} = NaN
        ln1_ut {mustBeMetadata(ln1_ut,-1,1,0)} = NaN
        ln2_ut {mustBeMetadata(ln2_ut,-1,1,0)} = NaN
        ln3_ut {mustBeMetadata(ln3_ut,-1,1,0)} = NaN
        ln4_ut {mustBeMetadata(ln4_ut,-1,1,0)} = NaN
        pn1_ut {mustBeMetadata(pn1_ut,0,500,0)} = NaN
        pn2_ut {mustBeMetadata(pn2_ut,0,500,0)} = NaN
        pn3_ut {mustBeMetadata(pn3_ut,0,500,0)} = NaN
        pn4_ut {mustBeMetadata(pn4_ut,0,500,0)} = NaN
    end
    methods
        function obj = EarthOrientation(options) %#codegen
            %EarthOrientation - Construct editable transformation metadata
            arguments
                options.?nfx.EarthOrientation
            end
            if isfield(options,'ta_pole'), obj.ta_pole = options.ta_pole; end
            if isfield(options,'a_pole'), obj.a_pole = options.a_pole; end
            if isfield(options,'b_pole'), obj.b_pole = options.b_pole; end
            if isfield(options,'cj1_pole'), obj.cj1_pole = options.cj1_pole; end
            if isfield(options,'cj2_pole'), obj.cj2_pole = options.cj2_pole; end
            if isfield(options,'dj1_pole'), obj.dj1_pole = options.dj1_pole; end
            if isfield(options,'dj2_pole'), obj.dj2_pole = options.dj2_pole; end
            if isfield(options,'pj1_pole'), obj.pj1_pole = options.pj1_pole; end
            if isfield(options,'pj2_pole'), obj.pj2_pole = options.pj2_pole; end
            if isfield(options,'e_pole'), obj.e_pole = options.e_pole; end
            if isfield(options,'f_pole'), obj.f_pole = options.f_pole; end
            if isfield(options,'gk1_pole'), obj.gk1_pole = options.gk1_pole; end
            if isfield(options,'gk2_pole'), obj.gk2_pole = options.gk2_pole; end
            if isfield(options,'hk1_pole'), obj.hk1_pole = options.hk1_pole; end
            if isfield(options,'hk2_pole'), obj.hk2_pole = options.hk2_pole; end
            if isfield(options,'pk1_pole'), obj.pk1_pole = options.pk1_pole; end
            if isfield(options,'pk2_pole'), obj.pk2_pole = options.pk2_pole; end
            if isfield(options,'tb_ut'), obj.tb_ut = options.tb_ut; end
            if isfield(options,'i_ut'), obj.i_ut = options.i_ut; end
            if isfield(options,'j_ut'), obj.j_ut = options.j_ut; end
            if isfield(options,'kn1_ut'), obj.kn1_ut = options.kn1_ut; end
            if isfield(options,'kn2_ut'), obj.kn2_ut = options.kn2_ut; end
            if isfield(options,'kn3_ut'), obj.kn3_ut = options.kn3_ut; end
            if isfield(options,'kn4_ut'), obj.kn4_ut = options.kn4_ut; end
            if isfield(options,'ln1_ut'), obj.ln1_ut = options.ln1_ut; end
            if isfield(options,'ln2_ut'), obj.ln2_ut = options.ln2_ut; end
            if isfield(options,'ln3_ut'), obj.ln3_ut = options.ln3_ut; end
            if isfield(options,'ln4_ut'), obj.ln4_ut = options.ln4_ut; end
            if isfield(options,'pn1_ut'), obj.pn1_ut = options.pn1_ut; end
            if isfield(options,'pn2_ut'), obj.pn2_ut = options.pn2_ut; end
            if isfield(options,'pn3_ut'), obj.pn3_ut = options.pn3_ut; end
            if isfield(options,'pn4_ut'), obj.pn4_ut = options.pn4_ut; end
        end
        function report = validate(obj) %#codegen
            %VALIDATE - Check exact Julian epochs and all required parameters
            report = newReport('GLAS/GFM EarthOrientation');
            reference = 'STDI-0002-2 Appendix M, Tables M.6-4 and M.6-6';
            report = addIssue(report,~julianDate(obj.ta_pole) || ~julianDate(obj.tb_ut), ...
                'JulianEpoch','ta_pole/tb_ut','Supply exact Julian-date text from 2000000.00000000000 through 3000000.00000000000.',reference);
            numbers = [obj.a_pole ...
                obj.b_pole ...
                obj.cj1_pole ...
                obj.cj2_pole ...
                obj.dj1_pole ...
                obj.dj2_pole ...
                obj.pj1_pole ...
                obj.pj2_pole ...
                obj.e_pole ...
                obj.f_pole ...
                obj.gk1_pole ...
                obj.gk2_pole ...
                obj.hk1_pole ...
                obj.hk2_pole ...
                obj.pk1_pole ...
                obj.pk2_pole ...
                obj.i_ut ...
                obj.j_ut ...
                obj.kn1_ut ...
                obj.kn2_ut ...
                obj.kn3_ut ...
                obj.kn4_ut ...
                obj.ln1_ut ...
                obj.ln2_ut ...
                obj.ln3_ut ...
                obj.ln4_ut ...
                obj.pn1_ut ...
                obj.pn2_ut ...
                obj.pn3_ut ...
                obj.pn4_ut];
            report = addIssue(report,any(isnan(numbers)),'Required','transformation parameters', ...
                'Supply every polar-wander and UT parameter; zero is a supplied value.',reference);
        end
        function value = bytes(obj) %#codegen
            %BYTES - Encode the 370-byte transformation block in field order
            requireValid(validate(obj));
            value = [ ...
                textField(obj.ta_pole,19) ...
                decimalField(obj.a_pole,11,8,true) ...
                decimalField(obj.b_pole,11,8,true) ...
                decimalField(obj.cj1_pole,11,8,true) ...
                decimalField(obj.cj2_pole,11,8,true) ...
                decimalField(obj.dj1_pole,11,8,true) ...
                decimalField(obj.dj2_pole,11,8,true) ...
                decimalField(obj.pj1_pole,10,6,false) ...
                decimalField(obj.pj2_pole,10,6,false) ...
                decimalField(obj.e_pole,11,8,true) ...
                decimalField(obj.f_pole,11,8,true) ...
                decimalField(obj.gk1_pole,11,8,true) ...
                decimalField(obj.gk2_pole,11,8,true) ...
                decimalField(obj.hk1_pole,11,8,true) ...
                decimalField(obj.hk2_pole,11,8,true) ...
                decimalField(obj.pk1_pole,10,6,false) ...
                decimalField(obj.pk2_pole,10,6,false) ...
                textField(obj.tb_ut,19) ...
                decimalField(obj.i_ut,12,9,true) ...
                decimalField(obj.j_ut,12,9,true) ...
                decimalField(obj.kn1_ut,12,9,true) ...
                decimalField(obj.kn2_ut,12,9,true) ...
                decimalField(obj.kn3_ut,12,9,true) ...
                decimalField(obj.kn4_ut,12,9,true) ...
                decimalField(obj.ln1_ut,12,9,true) ...
                decimalField(obj.ln2_ut,12,9,true) ...
                decimalField(obj.ln3_ut,12,9,true) ...
                decimalField(obj.ln4_ut,12,9,true) ...
                decimalField(obj.pn1_ut,10,6,false) ...
                decimalField(obj.pn2_ut,10,6,false) ...
                decimalField(obj.pn3_ut,10,6,false) ...
                decimalField(obj.pn4_ut,10,6,false) ...
                ];
        end
    end
end

function valid = julianDate(value) %#codegen
    %julianDate - Check bounds textually without losing fractional epoch bits
    value = char(value); valid = false;
    if numel(value) ~= 19 || value(8) ~= '.', return; end
    digits = value([1:7 9:19]);
    if any(digits < '0' | digits > '9'), return; end
    day = str2double(value(1:7));
    valid = day >= 2000000 && day <= 3000000 && ...
        (day ~= 3000000 || all(value(9:19) == '0'));
end
