function value = fixturePolynomial()
    %fixturePolynomial - Synthetic affine polynomial with explicit ground axes
    value = nfx.RSMPCA(iid='SYNTHETIC ORIGINAL',edition='NFX TEST 01',rsn=1,csn=1, ...
        rnrmo=0,cnrmo=0,xnrmo=0,ynrmo=0,znrmo=0, ...
        rnrmsf=1,cnrmsf=1,xnrmsf=1,ynrmsf=1,znrmsf=1, ...
        rnpcf=[0;1],rdpcf=1,cnpcf=[0 1],cdpcf=1);
end
