function validateImage(data)
    %validateImage - Accept dense CPU grayscale and RGB arrays
    classes = {'logical', 'uint8', 'uint16', 'uint32', 'int8', ...
        'int16', 'int32', 'single', 'double'};
    if ~any(strcmp(class(data), classes)) || issparse(data) || ...
            ~isreal(data) || isempty(data) || ndims(data) > 3 || ...
            ~ismember(size(data, 3), [1 3])
        error('twd:InvalidImage', ...
            ['Data must be a nonempty, dense, real grayscale or RGB ' ...
             'CPU array of logical, single, double, or 8/16/32-bit integers.']);
    end
end
