function result = nfxCoderTiming(deltas, multiplier) %#codegen
    %nfxCoderTiming - Probe exact uint64 timing and big-endian fields
    timing = nfx.MTIMSA(image_seg_index=1, layer_id='SYNTHETIC', ...
        camera_set_index=1, camera_id='10000000-0000-4000-8000-000000000001', ...
        time_interval_index=1, temp_block_index=1, nominal_frame_rate=1, ...
        base_timestamp='20260917120000.000000001', dt_multiplier=multiplier, ...
        number_frames=max(1, numel(deltas)), dt=deltas, dt_size=8);
    bytes = timing.payload(); [copy, ok, status] = nfx.MTIMSA.deserialize(bytes);
    result = struct('ok', ok, 'code', status.code, 'dt', copy.dt, ...
        'multiplier', copy.dt_multiplier, 'timestamp', copy.base_timestamp, ...
        'tail', bytes(end - 8 * numel(deltas) + 1:end));
end
