function value = emptyImageSource() %#codegen
    %emptyImageSource - Construct a value-only deferred image descriptor
    location = struct('headerOffset', 0, 'headerLength', 0, ...
        'dataOffset', 0, 'dataLength', 0);
    layout = struct('nrows', 0, 'ncols', 0, 'bands', 0, 'nbpp', 0, ...
        'nbpr', 0, 'nbpc', 0, 'imode', ' ', 'ic', '  ', 'comrat', '');
    area = struct('offset', 0, 'length', 0, 'overflow', 0);
    entry = struct('location', location, 'header', nfx.ImageHeader(), ...
        'layout', layout, 'user', area, 'extended', area);
    value = struct('path', '', 'length', 0, 'modified', 0, ...
        'fileHeader', zeros(1, 0, 'uint8'), ...
        'imageHeader', zeros(1, 0, 'uint8'), 'entry', entry, ...
        'j2klra', zeros(1, 0, 'uint8'), ...
        'frames', 1, 'index', 0, 'maxPixels', flintmax, 'maxBytes', flintmax);
end
