function valid = validImageSelection(value) %#codegen
    %validImageSelection - Recognize distinct one-based image indices
    valid = isa(value, 'double') && isreal(value) && ~issparse(value) && ...
        (isrow(value) || isempty(value)) && all(isfinite(value)) && ...
        all(value >= 1 & value <= 999 & fix(value) == value) && ...
        numel(unique(value)) == numel(value);
end
