function valid = validJPEG2000Options(backend, threads)
    %validJPEG2000Options - Check host decoder choices without coercion
    text = (ischar(backend) && isrow(backend)) || ...
        (isstring(backend) && isscalar(backend) && ~ismissing(backend));
    valid = text && any(strcmp(backend, {'auto', 'matlab', 'mex'})) && ...
        isa(threads, 'double') && isreal(threads) && isscalar(threads) && ...
        isfinite(threads) && threads >= 1 && threads <= double(intmax('int32')) && ...
        threads == fix(threads);
end
