function warned = warnMemory(bytes, threshold)
    %warnMemory - Warn about estimated buffers without imposing a limit
    warned = bytes > threshold;
    if warned
        warning('nfx:MemoryUsage', ...
            ['Estimated NFX buffers require %.2f GiB. Processing continues. ' ...
            'Codec workspace, MATLAB overhead, and caller-held copies can ' ...
            'increase peak memory. Set MemoryWarningBytes=Inf to silence ' ...
            'this warning; MaxBytes and MaxPixels remain explicit limits.'], ...
            bytes / 2^30);
    end
end
