function valid = illuminationDatum(datum,ellipsoid) %#codegen
    %illuminationDatum - Check Appendix P Tables P-16/P-17 registered pairing
    %   Pinned to the 02 April 2024 GeoSDE appendix. Blank table pairings
    %   leave the ellipsoid selection with the producer. Historical aliases
    %   are accepted explicitly. No datum conversion is performed.
    datum = strtrim(char(datum));
    ellipsoid = strtrim(char(ellipsoid));
    switch ellipsoid
        case 'AAY', ellipsoid = 'AA';
        case 'AAM', ellipsoid = 'AM';
        case 'CLK', ellipsoid = 'CC';
        case 'CLJ', ellipsoid = 'CD';
        case 'INT', ellipsoid = 'IN';
        case 'KRA', ellipsoid = 'KA';
        case 'WGC', ellipsoid = 'WD';
        case 'WGE', ellipsoid = 'WE';
    end
    ellipsoids = [ ...
        'AA'; 'AM'; 'AN'; 'AP'; 'AT'; 'AW'; 'BM'; 'BN'; 'BR'; 'CA'; 'CB'; 'CC'; ...
        'CD'; 'CE'; 'CF'; 'CG'; 'CI'; 'CJ'; 'CL'; 'DA'; 'DB'; 'DC'; 'EA'; 'EB'; ...
        'EC'; 'ED'; 'EE'; 'EF'; 'EV'; 'FA'; 'FC'; 'FM'; 'GE'; 'HA'; 'HE'; 'HO'; ...
        'IA'; 'ID'; 'IN'; 'KA'; 'KB'; 'NO'; 'NW'; 'PM'; 'PR'; 'RE'; 'RF'; 'SA'; ...
        'SG'; 'SJ'; 'SN'; 'ST'; 'SV'; 'WA'; 'WB'; 'WC'; 'WD'; 'WE'; 'WF'; 'WO'; ...
        'WS'; 'ZY'; 'ZZ'; ...
        ];
    pairs = [ ...
        'ADI CD '; 'ADIACD '; 'ADIBCD '; 'ADICCD '; 'ADIDCD '; 'ADIECD '; 'ADIFCD '; 'ADIMCD '; ...
        'AFG KA '; 'AIA CD '; 'AIN IN '; 'AINAIN '; 'AINBIN '; 'AMA CC '; 'AME BR '; 'ANO AN '; ...
        'APL CC '; 'ARF CD '; 'ARFACD '; 'ARFBCD '; 'ARFCCD '; 'ARFDCD '; 'ARFECD '; 'ARFFCD '; ...
        'ARFGCD '; 'ARFHCD '; 'ARFMCD '; 'ARS CD '; 'ARSACD '; 'ARSBCD '; 'ARSMCD '; 'ART CD '; ...
        'ASC IN '; 'ASM CD '; 'ASQ IN '; 'ATF IN '; 'ATX AT '; 'AUA AN '; 'AUG AN '; 'BAT BR '; ...
        'BAT1BR '; 'BEK CG '; 'BEL IN '; 'BER CC '; 'BID IN '; 'BJM KA '; 'BJZ KA '; 'BOO IN '; ...
        'BOO1IN '; 'BRE BR '; 'BRE1BR '; 'BUR BR '; 'CAC CC '; 'CAI IN '; 'CAM CD '; 'CAO IN '; ...
        'CAP CE '; 'CAZ IN '; 'CCD BR '; 'CGE CG '; 'CGX CC '; 'CHI IN '; 'CHU IN '; 'COA IN '; ...
        'COV CG '; 'CSG IN '; 'DAL CD '; 'DCS CD '; 'DID CD '; 'DOB IN '; 'DOM    '; 'EAS IN '; ...
        'ENW HO '; 'EUR IN '; 'EURAIN '; 'EURBIN '; 'EURCIN '; 'EURDIN '; 'EUREIN '; 'EURFIN '; ...
        'EURGIN '; 'EURHIN '; 'EURIIN '; 'EURJIN '; 'EURKIN '; 'EURLIN '; 'EURMIN '; 'EURSIN '; ...
        'EURTIN '; 'EUS IN '; 'EUT RF '; 'FAH CD '; 'FLO IN '; 'FOT CD '; 'GAA IN '; 'GAN IN '; ...
        'GDS RF '; 'GDZ IA '; 'GEO IN '; 'GIZ IN '; 'GRA IN '; 'GRK BR '; 'GRX RF '; 'GSE BR '; ...
        'GSF BR '; 'GUA CC '; 'HEN IN '; 'HER BR '; 'HIT IN '; 'HJO IN '; 'HKD IN '; 'HKO CA '; ...
        'HTN IN '; 'HUY RE '; 'IBE IN '; 'IDN ID '; 'IND    '; 'INDA   '; 'INDBEA '; 'INDIEC '; ...
        'INDPEF '; 'INF EA '; 'INFAEA '; 'ING EA '; 'INGAEA '; 'INGBEA '; 'INH EA '; 'INHAEA '; ...
        'IRL AM '; 'ISG IN '; 'IST IN '; 'JOH IN '; 'KAB EC '; 'KAN EA '; 'KEA EE '; 'KCS WO '; ...
        'KEG IN '; 'KGS RF '; 'KKX IN '; 'KUS IN '; 'KUW CD '; 'LCF CC '; 'LEH CD '; 'LIB CD '; ...
        'LIS    '; 'LOC    '; 'LOM IN '; 'LUZ CC '; 'LUZACC '; 'LUZBCC '; 'MAA IN '; 'MAR IN '; ...
        'MAS BR '; 'MAW    '; 'MCX IN '; 'MDT CB '; 'MER CG '; 'MID IN '; 'MIK CD '; 'MIN CD '; ...
        'MINACD '; 'MINBCD '; 'MOD IN '; 'MOD1IN '; 'MOL BR '; 'MPO CD '; 'MVS CD '; 'NAH CD '; ...
        'NAHACD '; 'NAHBCD '; 'NAHCCD '; 'NAP IN '; 'NAR RF '; 'NARARF '; 'NARBRF '; 'NARCRF '; ...
        'NARDRF '; 'NARERF '; 'NARHRF '; 'NAS CC '; 'NASACC '; 'NASBCC '; 'NASCCC '; 'NASDCC '; ...
        'NASECC '; 'NASFCC '; 'NASGCC '; 'NASHCC '; 'NASICC '; 'NASJCC '; 'NASLCC '; 'NASNCC '; ...
        'NASOCC '; 'NASPCC '; 'NASQCC '; 'NASRCC '; 'NASTCC '; 'NASUCC '; 'NASVCC '; 'NASWCC '; ...
        'NAX CD '; 'NFR1CD '; 'NSD CD '; 'OCO    '; 'ODU IN '; 'OEG HE '; 'OGB AA '; 'OGBAAA '; ...
        'OGBBAA '; 'OGBCAA '; 'OGBDAA '; 'OGBMAA '; 'OHA CC '; 'OHAACC '; 'OHABCC '; 'OHACCC '; ...
        'OHADCC '; 'OHAMCC '; 'OSL BM '; 'PAD BR '; 'PAD1BR '; 'PAL CF '; 'PDM IN '; 'PHA CD '; ...
        'PIT IN '; 'PLN IN '; 'POS IN '; 'PRP IN '; 'PRPAIN '; 'PRPBIN '; 'PRPCIN '; 'PRPDIN '; ...
        'PRPEIN '; 'PRPFIN '; 'PRPGIN '; 'PRPHIN '; 'PRPMIN '; 'PTB CD '; 'PTN CD '; 'PUK KA '; ...
        'PUR CC '; 'QAT IN '; 'QUO IN '; 'RAU BR '; 'REC CG '; 'REU IN '; 'RTS BR '; 'SAE IN '; ...
        'SAF CD '; 'SAG    '; 'SAN SA '; 'SANASA '; 'SANBSA '; 'SANCSA '; 'SANDSA '; 'SANESA '; ...
        'SANFSA '; 'SANGSA '; 'SANHSA '; 'SANISA '; 'SANJSA '; 'SANKSA '; 'SANLSA '; 'SANMSA '; ...
        'SAO IN '; 'SAP IN '; 'SCK BN '; 'SGA SG '; 'SGB SG '; 'SGM IN '; 'SHB IN '; 'SIB CD '; ...
        'SOA FA '; 'SPK KA '; 'SPX CC '; 'STO BR '; 'SYO CB '; 'TAN IN '; 'TAN1IN '; 'TDC IN '; ...
        'TIL EB '; 'TIN BR '; 'TOY BR '; 'TOYABR '; 'TOYBBR '; 'TOYCBR '; 'TOYMBR '; 'TRI CA '; ...
        'TRN IN '; 'UND    '; 'VOI CG '; 'VOI1CG '; 'WAK IN '; 'WGA WS '; 'WGB WC '; 'WGC WD '; ...
        'WGE WE '; 'YAC IN '; 'ZAN IN '; 'ZYX    '; 'FDA CD '; ...
        ];
    valid = false;
    ellipsoidValid = false;
    for k = 1:size(ellipsoids,1)
        ellipsoidValid = ellipsoidValid || strcmp(ellipsoid,ellipsoids(k,:));
    end
    if ~ellipsoidValid, return; end
    for k = 1:size(pairs,1)
        if strcmp(datum,strtrim(pairs(k,1:4)))
            expected = strtrim(pairs(k,5:7));
            valid = isempty(expected) || strcmp(expected,ellipsoid);
            return
        end
    end
end
