function known = knownTRE(tag) %#codegen
    %knownTRE - Identify tags whose payload schema NFX validates
    known = any(strcmp(tag, { ...
        'ACFTB ', 'AIMIDB', 'BANDSB', 'CAMSDA', 'CSCRNA', 'CSDIDA', ...
        'CSEXRB', 'CSRLSB', 'CSWRPB', 'FCRNSA', 'FREESA', 'HISTOA', ...
        'ICHIPB', 'ILLUMB', 'J2KLRA', 'MATESA', 'MICIDA', 'MIMCSA', ...
        'MTIMFA', 'MTIMSA', 'RPC00B', 'RSMAPB', 'RSMDCB', 'RSMECB', ...
        'RSMGGA', 'RSMGIA', 'RSMIDA', 'RSMPCA', 'RSMPIA', 'SENSRB', ...
        'TMINTA', 'FSYNWA', 'FASYWA', 'CONTXA'}));
end
