function known = knownTRE(tag) %#codegen
    %knownTRE - Identify tags whose payload schema NFX validates
    known = any(strcmp(tag, { ...
        'ACFTB ', 'AIMIDB', 'BANDSB', 'CAMSDA', 'CSCRNA', 'CSDIDA', ...
        'CSEXRB', 'CSRLSB', 'CSWRPB', 'FCRNSA', 'FREESA', 'HISTOA', ...
        'ICHIPB', 'ILLUMB', 'J2KLRA', 'MATESA', 'MICIDA', 'MIMCSA', ...
        'MTIMFA', 'MTIMSA', 'RPC00B', 'RSMAPB', 'RSMDCB', 'RSMECB', ...
        'RSMGGA', 'RSMGIA', 'RSMIDA', 'RSMPCA', 'RSMPIA', 'SENSRB', ...
        'TMINTA', 'FSYNWA', 'FASYWA', 'CONTXA', ...
        'GEOPSB', 'BNDPLC', 'XMLDCA', 'SECURA', 'PIXQLA', 'CSCCGA', ...
        'MSTGTA', 'BLOCKA', 'ENGRDA'}));
    % BEGIN published TRE recognition
    known = known || any(strcmp(tag, { ...
        'ACCHZB', ...
        'ACCPOB', ...
        'ACCVTB', ...
        'ASTORA', ...
        'ATTPTA', ...
        'BCHIPA', ...
        'BNDPLB', ...
        'CCINFA', ...
        'COMNTA', ...
        'CSEPHA', ...
        'CSEXRA', ...
        'CSPROA', ...
        'CSSFAA', ...
        'EXOPTA', ...
        'EXPLTB', ...
        'FACCBB', ...
        'GEOLOB', ...
        'GRDPSB', ...
        'IOMAPA', ...
        'ISACPA', ...
        'ISASIA', ...
        'ISATPA', ...
        'J2KLRB', ...
        'MAPLOB', ...
        'MENSRB', ...
        'MITOCA', ...
        'MTIRPB', ...
        'NBLOCA', ...
        'PATCHB', ...
        'PIAEQA', ...
        'PIAEVA', ...
        'PIAIMC', ...
        'PIAPEB', ...
        'PIAPRD', ...
        'PIATGB', ...
        'PIXMTA', ...
        'PRJPSB', ...
        'REGPTB', ...
        'REGPTC', ...
        'RELCCA', ...
        'RSMAPA', ...
        'RSMDCA', ...
        'RSMECA', ...
        'S2EVPA', ...
        'SECTGA', ...
        'SNSPSB', ...
        'SOURCB', ...
        'STDIDC', ...
        'STREOB', ...
        'SYSIDA', ...
        'USE00A'}));
    % END published TRE recognition
end
