function mustBeTRELookupTables(value) %#codegen
    if ~isa(value, 'uint8') || ~ismatrix(value) || issparse(value) || ...
            size(value, 2) > 3 || size(value, 1) > 65536 || ...
            (isempty(value) && ~isequal(size(value), [0 0]))
        error('nfx:LookupTables', ...
            'Supply a uint8 matrix with one to three lookup-table columns.');
    end
end
