function [obj, reader] = readEarthOrientation(reader) %#codegen
    %readEarthOrientation - Preserve exact epochs and bounded coefficients
    obj = nfx.EarthOrientation();
    [text, reader] = reader.text(19, false);
    if reader.ok, obj.ta_pole = text; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.a_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.b_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.cj1_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.cj2_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.dj1_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.dj2_pole = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pj1_pole = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pj2_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.e_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.f_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.gk1_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.gk2_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.hk1_pole = value; end
    [value, reader] = reader.number(11, -1, 1, false);
    if reader.ok, obj.hk2_pole = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pk1_pole = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pk2_pole = value; end
    [text, reader] = reader.text(19, false);
    if reader.ok, obj.tb_ut = text; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.i_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.j_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.kn1_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.kn2_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.kn3_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.kn4_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.ln1_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.ln2_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.ln3_ut = value; end
    [value, reader] = reader.number(12, -1, 1, false);
    if reader.ok, obj.ln4_ut = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pn1_ut = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pn2_ut = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pn3_ut = value; end
    [value, reader] = reader.number(10, 0, 500, false);
    if reader.ok, obj.pn4_ut = value; end
end
