function value = snipCitationData() %#codegen
    %snipCitationData - Encode the uncertified citation in SNIP Table 18-3
    lines = { ...
        'TEXT_SEGMENT_TITLE: STANDARD CITATIONS: Standards used to create this dataset.', ...
        'STANDARD CITATION 1', ...
        ['DOC_TITLE: National Imagery Transmission Format Version 2.1 Spectral NITF Implementation Profile ' ...
        '(SNIP) for Multispectral Imagery (MSI), Hyperspectral Imagery (HSI), and Other Spectroradiometric Imagery'], ...
        'DOC_VERSION: 1.2 CN1', ...
        'DOC_DATE: 2024-02-29', ...
        'DOC_ID: NGA.STND.0072_1.2_SNIP_CN1', ...
        'DOC_TYPE: National Geospatial-Intelligence Agency (NGA) Standardization Document Implementation Profile', ...
        'DOC_URL: https://nsgreg.nga.mil/doc/view?i=5612', ...
        'PRODUCT_CERT_DATE: ----------', ...
        'CUSTODIAN_ORG: Geospatial Intelligence Standards Working Group (GWG) NITFS Technical Board (NTB)', ...
        'CUSTODIAN_AGENCY: National Geospatial-Intelligence Agency (NGA)', ...
        'CUSTODIAN_EMAIL: NTBChair@nga.mil', ...
        'CUSTODIAN_ADDRESS: 7500 GEOINT Drive, Mail Stop N32, Springfield, Virginia 22150, USA', ...
        'CUSTODIAN_URL: https://gwg.nga.mil/gwg/focus-groups/NITFS_Technical_Board_(NTB).html', ...
        'CUSTODIAN_URL: https://gwg.nga.mil/'};
    value = '';
    for k = 1:numel(lines), value = [value lines{k} char([13 10])]; end %#ok<AGROW>
end
