function report = unverifiedSecurityDocument() %#codegen
    %unverifiedSecurityDocument - Expose the security document validation limit
    report = newReport('STDI-0002-1 Appendix AI');
    report.complete = false;
    report.issues(end + 1) = struct('severity', 'warning', ...
        'id', 'SecurityDocumentUnchecked', 'field', 'SECURA.security', ...
        'message', ['Security document bytes are preserved; XML, GZIP ' ...
            'and registered security-schema validation are external.'], ...
        'reference', report.scope);
end
