function valid = validGEOPSCode(code, category) %#codegen
    %validGEOPSCode - Match Appendix P registered and legacy datum codes
    %   STDI-0002-1 Appendix P (2024-04), Tables P-16..P-19 and P-21.
    switch category
        case 'ellipsoid'
            codes = { ...
                'AA', 'AAY', 'AM', 'AAM', 'AN', 'AP', 'AT', 'AW', ...
                'BM', 'BN', 'BR', 'CA', 'CB', 'CC', 'CLK', 'CD', ...
                'CLJ', 'CE', 'CF', 'CG', 'CI', 'CJ', 'CL', 'DA', ...
                'DB', 'DC', 'EA', 'EB', 'EC', 'ED', 'EE', 'EF', ...
                'EV', 'FA', 'FC', 'FM', 'GE', 'HA', 'HE', 'HO', ...
                'IA', 'ID', 'IN', 'INT', 'KA', 'KRA', 'KB', 'NO', ...
                'NW', 'PM', 'PR', 'RE', 'RF', 'SA', 'SG', 'SJ', ...
                'SN', 'ST', 'SV', 'WA', 'WB', 'WC', 'WD', 'WGC', ...
                'WE', 'WGE', 'WF', 'WO', 'WS', 'ZY', 'ZZ'};
        case 'datum'
            codes = { ...
                'ADI', 'ADIA', 'ADIB', 'ADIC', 'ADID', 'ADIE', ...
                'ADIF', 'ADIM', 'AFG', 'AIA', 'AIN', 'AINA', 'AINB', ...
                'AMA', 'AME', 'ANO', 'APL', 'ARF', 'ARFA', 'ARFB', ...
                'ARFC', 'ARFD', 'ARFE', 'ARFF', 'ARFG', 'ARFH', ...
                'ARFM', 'ARS', 'ARSA', 'ARSB', 'ARSM', 'ART', 'ASC', ...
                'ASM', 'ASQ', 'ATF', 'ATX', 'AUA', 'AUG', 'BAT', ...
                'BAT1', 'BEK', 'BEL', 'BER', 'BID', 'BJM', 'BJZ', ...
                'BOO', 'BOO1', 'BRE', 'BRE1', 'BUR', 'CAC', 'CAI', ...
                'CAM', 'CAO', 'CAP', 'CAZ', 'CCD', 'CGE', 'CGX', ...
                'CHI', 'CHU', 'COA', 'COV', 'CSG', 'DAL', 'DCS', ...
                'DID', 'DOB', 'DOM', 'EAS', 'ENW', 'EUR', 'EURA', ...
                'EURB', 'EURC', 'EURD', 'EURE', 'EURF', 'EURG', ...
                'EURH', 'EURI', 'EURJ', 'EURK', 'EURL', 'EURM', ...
                'EURS', 'EURT', 'EUS', 'EUT', 'FAH', 'FLO', 'FOT', ...
                'GAA', 'GAN', 'GDS', 'GDZ', 'GEO', 'GIZ', 'GRA', ...
                'GRK', 'GRX', 'GSE', 'GSF', 'GUA', 'HEN', 'HER', ...
                'HIT', 'HJO', 'HKD', 'HKO', 'HTN', 'HUY', 'IBE', ...
                'IDN', 'IND', 'INDA', 'INDB', 'INDI', 'INDP', 'INF', ...
                'INFA', 'ING', 'INGA', 'INGB', 'INH', 'INHA', 'IRL', ...
                'ISG', 'IST', 'JOH', 'KAB', 'KAN', 'KEA', 'KCS', ...
                'KEG', 'KGS', 'KKX', 'KUS', 'KUW', 'LCF', 'LEH', ...
                'LIB', 'LIS', 'LOC', 'LOM', 'LUZ', 'LUZA', 'LUZB', ...
                'MAA', 'MAR', 'MAS', 'MAW', 'MCX', 'MDT', 'MER', ...
                'MID', 'MIK', 'MIN', 'MINA', 'MINB', 'MOD', 'MOD1', ...
                'MOL', 'MPO', 'MVS', 'NAH', 'NAHA', 'NAHB', 'NAHC', ...
                'NAP', 'NAR', 'NARA', 'NARB', 'NARC', 'NARD', ...
                'NARE', 'NARH', 'NAS', 'NASA', 'NASB', 'NASC', ...
                'NASD', 'NASE', 'NASF', 'NASG', 'NASH', 'NASI', ...
                'NASJ', 'NASL', 'NASN', 'NASO', 'NASP', 'NASQ', ...
                'NASR', 'NAST', 'NASU', 'NASV', 'NASW', 'NAX', ...
                'NFR1', 'FDA', 'NSD', 'OCO', 'ODU', 'OEG', 'OGB', ...
                'OGBA', 'OGBB', 'OGBC', 'OGBD', 'OGBM', 'OHA', ...
                'OHAA', 'OHAB', 'OHAC', 'OHAD', 'OHAM', 'OSL', ...
                'PAD', 'PAD1', 'PAL', 'PDM', 'PHA', 'PIT', 'PLN', ...
                'POS', 'PRP', 'PRPA', 'PRPB', 'PRPC', 'PRPD', ...
                'PRPE', 'PRPF', 'PRPG', 'PRPH', 'PRPM', 'PTB', ...
                'PTN', 'PUK', 'PUR', 'QAT', 'QUO', 'RAU', 'REC', ...
                'REU', 'RTS', 'SAE', 'SAF', 'SAG', 'SAN', 'SANA', ...
                'SANB', 'SANC', 'SAND', 'SANE', 'SANF', 'SANG', ...
                'SANH', 'SANI', 'SANJ', 'SANK', 'SANL', 'SANM', ...
                'SAO', 'SAP', 'SCK', 'SGA', 'SGB', 'SGM', 'SHB', ...
                'SIB', 'SOA', 'SPK', 'SPX', 'STO', 'SYO', 'TAN', ...
                'TAN1', 'TDC', 'TIL', 'TIN', 'TOY', 'TOYA', 'TOYB', ...
                'TOYC', 'TOYM', 'TRI', 'TRN', 'UND', 'VOI', 'VOI1', ...
                'WAK', 'WGA', 'WGB', 'WGC', 'WGE', 'YAC', 'ZAN', ...
                'ZYX'};
        case 'sounding'
            codes = { ...
                'ALAT', 'AMLS', 'AMLT', 'AMLW', 'AMSL', 'CD', ...
                'ESLW', 'HAT', 'HHLT', 'HNHR', 'HRHW', 'HTHW', 'HW', ...
                'HWS', 'IGLD', 'ISHW', 'ISLW', 'LAT', 'LD', 'LLLT', ...
                'LLWS', 'LRLW', 'LTLW', 'LW', 'LWS', 'MHHW', 'MHRW', ...
                'MHW', 'MHWN', 'MHWS', 'MLLS', 'MLLW', 'MLW', ...
                'MLWN', 'MLWS', 'MSL', 'MTL', 'NLLW', 'NT', 'ST', ...
                'VILB', 'ZYX', 'ZZZ'};
        case 'grid'
            codes = { ...
                'AD', 'AF', 'AG', 'AI', 'AJ', 'AK', 'AL', 'AM', ...
                'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT', 'AU', ...
                'AV', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BC', 'BD', ...
                'BE', 'BF', 'BL', 'BO', 'BW', 'CB', 'CD', 'CE', ...
                'CF', 'CG', 'CH', 'CI', 'CJ', 'CK', 'CM', 'CN', ...
                'CO', 'CQ', 'CR', 'CT', 'CU', 'CV', 'CW', 'CX', ...
                'CY', 'CZ', 'DA', 'DB', 'DC', 'DD', 'DE', 'DJ', ...
                'DK', 'EA', 'EB', 'ED', 'EE', 'EF', 'EL', 'EO', ...
                'EP', 'ER', 'ET', 'FA', 'FB', 'FC', 'FD', 'FE', ...
                'FF', 'FI', 'FJ', 'FL', 'FO', 'FS', 'GA', 'GB', ...
                'GC', 'GE', 'GF', 'GG', 'GH', 'GI', 'GK', 'GL', ...
                'GN', 'GO', 'GP', 'GQ', 'GR', 'GT', 'GU', 'GV', ...
                'GW', 'GY', 'HB', 'HC', 'HD', 'HE', 'HF', 'HG', ...
                'HR', 'IA', 'IB', 'IC', 'ID', 'IE', 'IF', 'IG', ...
                'IH', 'IJ', 'IK', 'IL', 'IN', 'IP', 'IQ', 'IR', ...
                'IT', 'IY', 'IZ', 'JA', 'JB', 'JC', 'JM', 'JO', ...
                'KA', 'KB', 'KC', 'KD', 'KE', 'KF', 'KG', 'KH', ...
                'KJ', 'KK', 'KL', 'KN', 'KT', 'KW', 'KX', 'LC', ...
                'LD', 'LE', 'LF', 'LG', 'LI', 'LK', 'LL', 'MA', ...
                'MB', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MI', ...
                'MJ', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', ...
                'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'NA', 'NB', ...
                'NC', 'ND', 'NE', 'NF', 'NG', 'NH', 'NI', 'NJ', ...
                'NK', 'NL', 'NM', 'NN', 'NO', 'NP', 'NQ', 'NR', ...
                'NS', 'NT', 'NU', 'NV', 'NW', 'NX', 'NY', 'NZ', ...
                'OA', 'OB', 'OD', 'OE', 'OR', 'OS', 'PA', 'PB', ...
                'PC', 'PD', 'PE', 'PF', 'PG', 'PI', 'PJ', 'PK', ...
                'PL', 'PP', 'PQ', 'PR', 'PS', 'PT', 'PU', 'QA', ...
                'QU', 'RB', 'RC', 'RD', 'RE', 'RF', 'RH', 'RI', ...
                'RK', 'RT', 'SA', 'SB', 'SD', 'SE', 'SF', 'SH', ...
                'SI', 'SJ', 'SK', 'SL', 'SN', 'SQ', 'SR', 'SS', ...
                'SV', 'SX', 'SY', 'SZ', 'TA', 'TB', 'TC', 'TD', ...
                'TE', 'TF', 'TG', 'TH', 'TI', 'TN', 'UA', 'UB', ...
                'UC', 'UD', 'UP', 'US', 'UT', 'VA', 'VB', 'VE', ...
                'VI', 'VL', 'WA', 'WB', 'WC', 'WD', 'WE', 'WF', ...
                'WH', 'WP', 'YA', 'YG', 'YU'};
        case 'vertical'
            codes = { ...
                'GEOD', 'MSL'};
        otherwise
            codes = {''};
    end
    valid = any(strcmp(strtrim(char(code)), codes));
end
