function collection = compressedCollectionExample(encoder)
    %compressedCollectionExample - Build two synthetic compressed motion frames
    %   COLLECTION = compressedCollectionExample(ENCODER) uses the OpenJPEG
    %   executable at ENCODER. Inspect COLLECTION.plan(), then write it to an
    %   existing folder with COLLECTION.write(FOLDER). No files are published
    %   by this example; compression uses temporary codec staging files.
    %
    %   The camera, identifiers, timing and pixels below are synthetic input.
    %   Applications supply their own metadata and choose their segmentation.
    %
    %   See also nfx.MIECollection, nfx.MotionBlock, nfx.ImageSegment.compress
    arguments
        encoder {mustBeTextScalar, mustBeNonzeroLengthText}
    end

    cameraID = '10000000-0000-4000-8000-000000000001';
    header = nfx.FileHeader(ostaid='SYNTHETIC', fsclas='U', ...
                           fdt='20261002120000');
    layer = nfx.MIMCSA(layer_id='VISIBLE', nominal_frame_rate=25, ...
                      min_frame_rate=25, max_frame_rate=25, ...
                      mi_req_decoder='C8', ...
                      mi_req_profile='ISO/IEC 15444-1', ...
                      mi_req_level='class2');
    camera = struct('camera_id', cameraID, ...
                    'camera_desc', 'Synthetic camera', ...
                    'layer_id', 'VISIBLE', 'idlvl', 1, 'ialvl', 0, ...
                    'iloc', [0 0], 'nrows', 64, 'ncols', 96);
    sets = nfx.CAMSDA(camera_sets=struct('cameras', camera));
    core = nfx.MICIDA.coreIdentifier(32, {cameraID});
    ids = nfx.MICIDA(cameras=nfx.MICIDA.camera(cameraID, core));
    interval = struct('time_interval_index', 1, ...
                      'start_timestamp', '20261002120000.000000000', ...
                      'end_timestamp', '20261002120000.080000000');
    collection = nfx.MIECollection(base_name='compressed', header=header, ...
                                   layers=layer, camera_sets=sets, ...
                                   camera_ids=ids, ...
                                   intervals=nfx.TMINTA(interval));

    boundaries = {'20261002120000.000000000', ...
                  '20261002120000.040000000', ...
                  '20261002120000.080000000'};
    for k = 1:2
        pixels = reshape(uint16(1:64*96), 64, 96) + uint16(k);
        imageHeader = nfx.ImageHeader(iid1=sprintf('FRAME%d', k), ...
                                     idatim='20261002120000', isclas='U', ...
                                     irep='MONO', icat='VIS.M');
        image = nfx.ImageSegment(pixels, header=imageHeader);
        image = image.compress(encoder, Profile='NPJE');

        timing = nfx.MTIMSA(camera_id=cameraID, time_interval_index=1, ...
                           nominal_frame_rate=25, reference_frame_num=1, ...
                           base_timestamp=boundaries{k}, ...
                           dt_multiplier=uint64(1000000), ...
                           dt=zeros(1, 0, 'uint64'));
        block = nfx.MotionBlock(image, timing=timing, ...
                               start_timestamp=boundaries{k}, ...
                               end_timestamp=boundaries{k + 1});
        collection = collection + block;
    end
end
