function collection = mieExample()
    %mieExample - Construct a synthetic two-layer motion collection
    %   COLLECTION = mieExample returns two camera sets, three cameras,
    %   two time intervals, and a manifest with one supplied quick look.
    %   All identifiers, imagery and timing are synthetic demonstrations.
    %
    %   Run FILES = COLLECTION.plan() to inspect the five output files.
    %   COLLECTION.write(FOLDER) writes to an existing destination folder.
    %
    %   See also nfx.MIECollection, nfx.MotionBlock

    header = nfx.FileHeader(ostaid='NFXDEMO', fdt='20260915120100', ...
        fsclas='U', ftitle='Synthetic MIE collection');
    camera = struct( ...
        'camera_id', '', 'camera_desc', 'Synthetic camera', ...
        'layer_id', 'VIS', 'idlvl', 1, 'ialvl', 0, ...
        'iloc', [0 0], 'nrows', 5, 'ncols', 7);
    cameras = repmat(camera, 1, 3);
    cores = repmat(nfx.MICIDA.camera('', ''), 1, 3);

    for k = 1:3
        id = sprintf('10000000-0000-4000-8000-%012.0f', k);
        cameras(k).camera_id = id;
        cameras(k).idlvl = k;
        cores(k) = nfx.MICIDA.camera( ...
            id, nfx.MICIDA.coreIdentifier(32, {id}));
    end

    cameras(2).layer_id = 'IR';
    cameras(2).iloc = [0 7];
    cameras(3).iloc = [5 0];
    sets = [struct('cameras', cameras(1:2)) struct('cameras', cameras(3))];

    layers = [ ...
        nfx.MIMCSA(layer_id='VIS', nominal_frame_rate=25, ...
            min_frame_rate=25, max_frame_rate=25, mi_req_decoder='NC', ...
            mi_req_profile='Not Applicable', mi_req_level='N/A') ...
        nfx.MIMCSA(layer_id='IR', nominal_frame_rate=20, ...
            min_frame_rate=20, max_frame_rate=20, mi_req_decoder='NC', ...
            mi_req_profile='Not Applicable', mi_req_level='N/A')];
    windows = [ ...
        struct('time_interval_index', 1, ...
            'start_timestamp', '20260915120000.000000000', ...
            'end_timestamp', '20260915120001.000000000') ...
        struct('time_interval_index', 2, ...
            'start_timestamp', '20260915120001.000000000', ...
            'end_timestamp', '20260915120002.000000000')];
    collection = nfx.MIECollection(base_name='mie-demo', header=header, ...
        layers=layers, camera_sets=nfx.CAMSDA(camera_sets=sets), ...
        camera_ids=nfx.MICIDA(cameras=cores), ...
        intervals=nfx.TMINTA(windows));

    for interval = 1:2
        for k = 1:3
            bands = 2;
            type = 'uint16';
            rate = 25;
            representation = 'MULTI';
            category = 'MS';

            if k == 2
                bands = 1;
                type = 'uint8';
                rate = 20;
                representation = 'MONO';
                category = 'IR';
            end

            data = reshape( ...
                cast(1:5 * 7 * bands * 3, type), 5, 7, bands, 3);
            image = nfx.ImageSegment(data, header=nfx.ImageHeader( ...
                iid1='SYNTHETIC', idatim='20260915120000', isclas='U', ...
                irep=representation, icat=category, nppbh=4, nppbv=3));
            timing = nfx.MTIMSA(camera_id=cameras(k).camera_id, ...
                time_interval_index=interval, nominal_frame_rate=rate, ...
                base_timestamp=windows(interval).start_timestamp, ...
                dt_multiplier=uint64(1000000), dt=uint64(1000 / rate));
            collection = collection + nfx.MotionBlock(image, ...
                timing=timing, ...
                start_timestamp=windows(interval).start_timestamp, ...
                end_timestamp=windows(interval).end_timestamp);
        end
    end

    quick = nfx.ImageSegment(uint8([0 64; 128 255]), ...
        header=nfx.ImageHeader( ...
            iid1='QUICKLOOK', idatim='20260915120000', ...
            isclas='U', irep='MONO', icat='VIS', nppbh=2, nppbv=2, ...
            icom=['Synthetic supplied overview; ' ...
                  'no resampling is performed.']));
    collection.quicklooks = quick + nfx.MTIMSA(image_seg_index=1, ...
        camera_set_index=0, time_interval_index=0, temp_block_index=0, ...
        nominal_frame_rate=0, ...
        base_timestamp=windows(1).start_timestamp, ...
        number_frames=1);
end
