function file = rsmExample()
    %rsmExample - Construct a synthetic adjusted RSM image
    %   FILE = rsmExample constructs a complete generic NITF value without
    %   writing a file. The pixels, model, identifiers, dates, adjustments
    %   and covariance are synthetic and have no scientific calibration.
    %
    %   Add src and examples to the MATLAB path, then write the result:
    %       file = rsmExample();
    %       file.write(fullfile(tempdir, 'nfx-rsm-example.ntf'));
    %
    %   See also nfx.File, nfx.RSMIDA, nfx.RSMPCA, nfx.RSMParameters

    identifier = 'NFX SYNTHETIC ORIGINAL';
    edition = 'NFX SYNTHETIC RSM 01';

    identification = nfx.RSMIDA( ...
        iid=identifier, edition=edition, grndd='G', ...
        fullr=5, fullc=7, minr=0, maxr=4, minc=0, maxc=6, ...
        v1x=0,    v1y=0,    v1z=0, ...
        v2x=0.01, v2y=0,    v2z=0, ...
        v3x=0,    v3y=0.01, v3z=0, ...
        v4x=0.01, v4y=0.01, v4z=0, ...
        v5x=0,    v5y=0,    v5z=1000, ...
        v6x=0.01, v6y=0,    v6z=1000, ...
        v7x=0,    v7y=0.01, v7z=1000, ...
        v8x=0.01, v8y=0.01, v8z=1000);

    polynomial = nfx.RSMPCA( ...
        iid=identifier, edition=edition, rsn=1, csn=1, ...
        rnrmo=0, cnrmo=0, xnrmo=0, ynrmo=0, znrmo=0, ...
        rnrmsf=1, cnrmsf=1, xnrmsf=1, ynrmsf=1, znrmsf=1, ...
        rnpcf=[0; 400], rdpcf=1, cnpcf=[0 600], cdpcf=1);

    parameters = nfx.RSMParameters(nsfx=1, nsfy=1, nsfz=1, ...
        noffx=0, noffy=0, noffz=0, ...
        xpwrr=0, ypwrr=0, zpwrr=0, xpwrc=0, ypwrc=0, zpwrc=0);
    adjustments = nfx.RSMAPB( ...
        iid=identifier, edition=edition, tid='SYNTHETIC ADJUSTMENT', ...
        parameters=parameters, parval=[0.01 -0.02]);
    covariance = nfx.RSMDCB( ...
        iid=identifier, edition=edition, tid=adjustments.tid, ...
        parameters=parameters, ...
        blocks=nfx.RSMDCB.block(identifier, [0.04 0.01; 0.01 0.09]));

    header = nfx.ImageHeader(iid1='RSM_DEMO', idatim='20260915120000', ...
        isclas='U', irep='MONO', icat='VIS', nppbh=4, nppbv=3);
    image = nfx.ImageSegment(reshape(uint16(1:35), 5, 7), header=header);
    image = image + identification + polynomial + adjustments + covariance;
    file = nfx.File(header=nfx.FileHeader( ...
        ostaid='NFXDEMO', fdt='20260915120000', ...
        fsclas='U', ftitle='Synthetic RSM demonstration')) + image;
end
