function file = snipExample()
    %snipExample - Assemble synthetic airborne MSI with a supplied RSM set
    %   FILE = snipExample returns a value that passes NFX's supported SNIP
    %   metadata checks. Every sample, model, date and contact is
    %   synthetic; the example has no calibration, scientific accuracy or
    %   certification.
    %
    %   Add src and examples to the MATLAB path, then inspect and write:
    %       file = snipExample();
    %       report = file.validate(SNIP_COMPLIANT=true);
    %       name = fullfile(tempdir, [file.header.ftitle '.ntf']);
    %       file.write(name, SNIP_COMPLIANT=true);
    %
    %   See also nfx.File, nfx.snipCitation, nfx.BANDSB

    h = nfx.FileHeader( ...
        ostaid='NFXDEMO', fdt='20260915120100', fsclas='U', ...
        ftitle='20260915120000_AG3607_DEMO_MSI_V1', ...
        oname='NFX DEMO', ophone='202-555-0101');
    imageHeader = nfx.ImageHeader( ...
        iid1='MULTISPECT', iid2='SYNTHETIC MSI ORIGINAL', ...
        isorce='AG3607', idatim='20260915120000', isclas='U', ...
        irep='MULTI', icat='MS', nppbh=4, nppbv=3, ...
        icords='D', isubcat=[450 650], ...
        igeolo=['+40.000-075.000' '+40.000-074.000' ...
                '+39.000-074.000' '+39.000-075.000']);

    bands = nfx.BANDSB(band=[ ...
        nfx.SpectralBand(bandid='B1', cwave=.45, fwhm=.05) ...
        nfx.SpectralBand(bandid='B2', cwave=.65, fwhm=.05)], ...
        wave_length_unit='U', ...
        row_gsd=1, row_gsd_unit='M', col_gsd=1, col_gsd_unit='M', ...
        spt_resp_row=1, spt_resp_unit_row='M', ...
        spt_resp_col=1, spt_resp_unit_col='M');
    corners = nfx.CSCRNA(predict_corners='N', ...
        ulcrn_lat=40, ulcrn_lon=-75, ulcrn_ht=100, ...
        urcrn_lat=40, urcrn_lon=-74, urcrn_ht=100, ...
        lrcrn_lat=39, lrcrn_lon=-74, lrcrn_ht=100, ...
        llcrn_lat=39, llcrn_lon=-75, llcrn_ht=100);

    event = nfx.HistoryEvent( ...
        pdate=h.fdt, psite=h.ostaid, pas='NFX DEMO', ibpp=8, obpp=8, ...
        ipcom=char('PROCEV_Format Conversion from MATLAB to NITF', ...
                   'ALGO_NFX synthetic example 1'));
    history = nfx.HISTOA(systype='9I00GA', pe='NONE', event=event);

    illumination = nfx.ILLUMB( ...
        lbound=.4, ubound=.7, datetime=imageHeader.idatim, ...
        target_lat=39.5, target_lon=-74.5, target_hgt=100, ...
        vertical_datum_ref='Geodetic', vertical_ref_code='GEOD', ...
        sensor_azimuth=180, sensor_elev=70);
    aircraft = nfx.ACFTB( ...
        sensor_id_type='MMFR', sensor_id='AG3607', ...
        mplan=24, pdate='20260915');
    acquisition = nfx.AIMIDB(acquisition_date=imageHeader.idatim);

    id = nfx.RSMIDA(iid=imageHeader.iid2, edition='NFX DEMO 01', ...
        sid=imageHeader.isorce, stid='MSI_RSM', ...
        grndd='G', fullr=5, fullc=7, minr=0, maxr=4, minc=0, maxc=6, ...
        v1x=0,   v1y=0,   v1z=0, ...
        v2x=.01, v2y=0,   v2z=0, ...
        v3x=0,   v3y=.01, v3z=0, ...
        v4x=.01, v4y=.01, v4z=0, ...
        v5x=0,   v5y=0,   v5z=1000, ...
        v6x=.01, v6y=0,   v6z=1000, ...
        v7x=0,   v7y=.01, v7z=1000, ...
        v8x=.01, v8y=.01, v8z=1000);
    polynomial = nfx.RSMPCA( ...
        iid=id.iid, edition=id.edition, rsn=1, csn=1, ...
        rnrmo=0, cnrmo=0, xnrmo=0, ynrmo=0, znrmo=0, ...
        rnrmsf=1, cnrmsf=1, xnrmsf=1, ynrmsf=1, znrmsf=1, ...
        rnpcf=[0; 1], rdpcf=1, cnpcf=[0 1], cdpcf=1);
    correlation = nfx.RSMCorrelation(corseg=[1 0], tauseg=[0 1]);
    covariance = nfx.RSMECB( ...
        iid=id.iid, edition=id.edition, tid='SYNTHETIC', ...
        urr=1, urc=0, ucc=1, ...
        row_correlation=correlation, column_correlation=correlation);

    image = nfx.ImageSegment(reshape(uint8(128:197), 5, 7, 2), ...
        header=imageHeader) ...
        + bands + corners + history + illumination + aircraft ...
        + acquisition + id + polynomial + covariance;
    dataset = nfx.CSDIDA( ...
        platform_code='9I', sensor_id='GA', product_id='P2', ...
        time=imageHeader.idatim, process_time=h.fdt, ...
        software_version_number='NFX DEMO 1');
    file = nfx.File(header=h) + dataset + image + nfx.snipCitation(h, 1);
end
