function report = summarize(config, tests)
    %summarize - Archive readable outcomes without converting skips to success
    listing = dir(fullfile(config.folder, '*', 'result.json'));
    records = struct([]);
    for k = 1:numel(listing)
        item = jsondecode(fileread(fullfile(listing(k).folder, listing(k).name)));
        records = [records item]; %#ok<AGROW>
    end
    if isempty(records)
        % Class setup can fail before the first probe writes a JSON record.
        % Retain a valid empty schema so framework diagnostics are archived.
        records = repmat(struct('probe', '', 'phase', '', 'outcome', ''), 1, 0);
    end
    passed = strcmp({records.outcome}, 'pass');
    report = struct('folder', config.folder, 'archive', '', ...
        'referencePasses', nnz(passed & strcmp({records.phase}, 'reference')), ...
        'mexPasses', nnz(passed & strcmp({records.phase}, 'mex')), ...
        'phaseResults', records, 'tests', struct([]), ...
        'allRequestedPassed', false);
    report.tests = repmat(struct('name', '', 'passed', false, 'failed', false, ...
        'incomplete', false, 'duration', 0), 1, numel(tests));
    for k = 1:numel(tests)
        report.tests(k) = struct('name', tests(k).Name, 'passed', tests(k).Passed, ...
            'failed', tests(k).Failed, 'incomplete', tests(k).Incomplete, ...
            'duration', tests(k).Duration);
    end
    report.allRequestedPassed = ~isempty(tests) && ~any([tests.Failed]) && ...
        numel(records) == numel(tests) && ...
        all(passed | strcmp({records.outcome}, 'not_requested'));
    [fid, message] = fopen(fullfile(config.folder, 'SUMMARY.md'), 'w', 'n', 'UTF-8');
    if fid < 0, error('nfxkit:SummaryWrite', '%s', message); end
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '# NFX Coder result summary\n\n');
    fprintf(fid, 'MATLAB %s (%s), %s.\n\n', config.environment.version, ...
        config.environment.release, config.environment.architecture);
    fprintf(fid, 'MATLAB reference passes: %d. MEX execution passes: %d.\n\n', ...
        report.referencePasses, report.mexPasses);
    fprintf(fid, ['Only a passing mex phase proves generated execution for its entry\n' ...
        'point and tested inputs. Standalone/noheap phases generate source only.\n' ...
        'A skipped or unavailable check is not a compilation pass.\n\n']);
    fprintf(fid, '| Probe | Phase | Outcome |\n|---|---|---|\n');
    for k = 1:numel(records)
        fprintf(fid, '| %s | %s | %s |\n', records(k).probe, ...
            records(k).phase, records(k).outcome);
    end
    fprintf(fid, ['\nSee results.json for case diagnostics; session.json for products and\n' ...
        'compilers; source-hashes.json for source identity; each probe folder\n' ...
        'for generation logs, exact configurations, sources, and reports.\n']);
end
