function value = fixtureSensor()
    %fixtureSensor - Minimal supplied sensor metadata with known reference
    value = nfx.SENSRB(sensor='TEST SENSOR',platform='TEST PLATFORM', ...
        operation_domain='Airborne',start_date='20260915',end_date='20260915', ...
        start_time=43200,end_time=43201,reference_time=0, ...
        latitude_or_x=40,longitude_or_y=-105,altitude_or_z=1000);
end
