function obj = fixtureRSMGrid()
    %fixtureRSMGrid - Supply a small synthetic two-plane correspondence grid
    plane = nfx.RSMGGA.plane([0 0;1 1],[0 1;0 1]);
    obj = nfx.RSMGGA(iid='SYNTHETIC ORIGINAL',edition='NFX TEST 01', ...
        ggrsn=1,ggcsn=1,deltax=0.01,deltay=0.01,deltaz=1000, ...
        xipln1=0,yipln1=0,zpln1=0,refrow=0,refcol=0, ...
        fnumrd=1,fnumcd=1,planes=[plane plane]);
end
