function [file,image,metadata] = fixtureSNIP()
    %fixtureSNIP - Synthetic metadata-only conformance fixture, not calibrated
    fileHeader = nfx.FileHeader(ostaid='NFXTEST',fdt='20260915120100',fsclas='U', ...
        ftitle='20260915120000_AG3607_TEST_MSI_V1',oname='NFX TEST',ophone='202-555-0101');
    header = nfx.ImageHeader(iid1='MULTISPECT',iid2='SYNTHETIC ORIGINAL',isorce='AG3607', ...
        idatim='20260915120000',isclas='U',irep='MULTI',icat='MS',nppbh=4,nppbv=3, ...
        icords='D',igeolo='+40.000-075.000+40.000-074.000+39.000-074.000+39.000-075.000', ...
        isubcat=[450 650]);
    metadata.bands = nfx.BANDSB(band=[nfx.SpectralBand(bandid='B1',cwave=.45,fwhm=.05) ...
        nfx.SpectralBand(bandid='B2',cwave=.65,fwhm=.05)],wave_length_unit='U', ...
        row_gsd=1,row_gsd_unit='M',col_gsd=1,col_gsd_unit='M', ...
        spt_resp_row=1,spt_resp_unit_row='M',spt_resp_col=1,spt_resp_unit_col='M');
    event = fixtureHistoryEvent(); event.ibpp = 8; event.obpp = 8;
    event.ipcom = char('PROCEV_Format Conversion from MATLAB to NITF','ALGO_NFX synthetic fixture 1');
    metadata.history = nfx.HISTOA(systype='9I00GA',pe='NONE',event=event);
    metadata.illumination = nfx.ILLUMB(lbound=.4,ubound=.7,datetime=header.idatim, ...
        target_lat=39.5,target_lon=-74.5,target_hgt=100,vertical_datum_ref='Geodetic', ...
        vertical_ref_code='GEOD',sensor_azimuth=180,sensor_elev=70);
    metadata.aircraft = fixtureAircraft(); metadata.identification = fixtureRSMIdentification();
    metadata.identification.sid = 'AG3607'; metadata.identification.stid = 'MSI_RSM';
    correlation = nfx.RSMCorrelation(corseg=[1 0],tauseg=[0 1]);
    metadata.covariance = nfx.RSMECB(iid=header.iid2,edition=metadata.identification.edition, ...
        tid='SYNTHETIC',urr=1,urc=0,ucc=1,row_correlation=correlation,column_correlation=correlation);
    image = nfx.ImageSegment(reshape(uint8(128:197),5,7,2),header=header)+ ...
        metadata.bands+fixtureCorners()+metadata.history+metadata.illumination+metadata.aircraft+ ...
        nfx.AIMIDB(acquisition_date=header.idatim)+metadata.identification+fixturePolynomial()+metadata.covariance;
    metadata.dataset = nfx.CSDIDA(platform_code='9I',sensor_id='GA',product_id='P2', ...
        time=header.idatim,process_time=fileHeader.fdt,software_version_number='NFX TEST 1');
    file = nfx.File(header=fileHeader)+metadata.dataset+image+nfx.snipCitation(fileHeader,1);
end
