function value = fullBandMetadata()
    %fullBandMetadata - Supplied synthetic values for all compatible groups
    a = nfx.SpectralBand(bandid='BAND ONE',bad_band=1,niirs=NaN,focal_len=200, ...
        fwhm=.05,fwhm_unc=.001,nom_wave=.45,nom_wave_unc=.002, ...
        scale_factor=2,additive_factor=-1,start_time='260915120000.001', ...
        int_time=.00001,caldrk=.1,calibration_sensitivity=.01, ...
        row_gsd=.25,row_gsd_unc=.001,row_gsd_unit='M',col_gsd=.5,col_gsd_unc=.01,col_gsd_unit='R', ...
        bknoise=.002,scnnoise=.003,spt_resp_function_row=.4,spt_resp_unc_row=.002,spt_resp_unit_row='M', ...
        spt_resp_function_col=.6,spt_resp_unc_col=.003,spt_resp_unit_col='R', ...
        data_fld_3=uint8(0:15),data_fld_4=uint8(16:39),data_fld_5=uint8(40:71),data_fld_6=uint8(72:119));
    b = a; b.bandid = 'BAND TWO'; b.niirs = 12; b.focal_len = 250;
    b.start_time = '26----120000.---'; b.int_time = 999999;
    bandAux = [struct('bapf','I','ubap','UNIT','apn',[-12 9999999999],'apr',[],'apa','') ...
        struct('bapf','R','ubap','M','apn',[],'apr',[.5 -2],'apa','') ...
        struct('bapf','A','ubap','UNIT','apn',[],'apr',[],'apa',char('red','green'))];
    cubeAux = [struct('capf','I','ucap','UNIT','apn',-999999999,'apr',[],'apa','') ...
        struct('capf','R','ucap','M/S','apn',[],'apr',.25,'apa','') ...
        struct('capf','A','ucap','UNIT','apn',[],'apr',[],'apa','clear')];
    value = nfx.BANDSB(band=[a b],radiometric_quantity='REFLECTANCE',radiometric_quantity_unit='P', ...
        scale_factor=.5,additive_factor=-2,row_gsd=.25,row_gsd_unit='M',col_gsd=.5,col_gsd_unit='M', ...
        spt_resp_row=.4,spt_resp_unit_row='M',spt_resp_col=.6,spt_resp_unit_col='M', ...
        radiometric_adjustment_surface='WITHIN ATMOSPHERE',atmospheric_adjustment_altitude=1000, ...
        diameter=10,data_fld_1=uint8(255:-1:208),data_fld_2=uint8(128:159),wave_length_unit='U', ...
        aux_b=bandAux,aux_c=cubeAux);
end
